cpu:
  background_cores:
  - 8
  - 9
  - 10
  - 11
  disable_core_parking: true
  high_performance_plan: true
  max_threads: 8
  performance_cores:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  precision_boost_overdrive: true
  simultaneous_multithreading: true
  thread_affinity_enabled: true
  thread_timeout: 30
  ryzen_9_5900x_optimized: true
extensions:
  recipe_creator:
    enabled: true
    output_dir: recipes
    template_path: templates\recipe_template.docx
gpu:
  cuda_compute_type: float16
  cuda_graphs: true
  cuda_memory_pool: true
  cuda_streams: 3
  dynamic_memory: true
  fragmentation_threshold: 15
  max_batch_size: 16
  max_percent: 90
  model_unload_threshold: 95
  pre_allocation: true
  reserved_memory_mb: 256
  tensor_cores_enabled: true
  tensor_precision: tf32
  rtx_3080_optimized: true
inactivity_timeout: 60
llm:
  attention_optimization: true
  batch_size: 16
  context_length: 8192
  gpu_layer_auto_adjust: true
  gpu_layers: 32
  kv_cache_optimization: true
  mixed_precision_enabled: true
  model_path: maggie/models/llm/neuralmagic-Mistral-7B-Instruct-v0.3-GPTQ-4bit
  model_type: mistral
  offload_strategy: auto
  precision_type: float16
  tensor_cores_enabled: true
  use_autogptq: true
  vram_efficient_loading: true
  rtx_3080_optimized: true
logging:
  async_enabled: true
  batch_size: 50
  batch_timeout: 5.0
  console_level: INFO
  file_level: DEBUG
  path: logs
memory:
  cache_size_mb: 6144
  defragmentation_threshold: 70
  large_pages_enabled: true
  max_percent: 75
  min_free_gb: 4
  model_unload_threshold: 85
  numa_aware: true
  preload_models: true
  xpg_d10_memory: true
stt:
  wake_word:
    access_key: 9hQNkT59LV9YLj02ilmzaIg4zqUjX0YycaHTcHPEJuQ1/58G/r4BXA==
    cpu_threshold: 5.0
    dedicated_core: 0
    dedicated_core_enabled: true
    engine: porcupine
    keyword: maggie
    keyword_path: \maggie\models\stt\porcupine\Hey-Maggie_en_windows_v3_0_0.ppn
    minimal_processing: true
    pvporcupine_version: 3.0.2
    real_time_priority: true
    sensitivity: 0.5
    use_sounddevice: true
  whisper:
    cache_models: true
    chunk_size: 512
    compute_type: float16
    flash_attention_enabled: true
    max_batch_size: 16
    memory_efficient: true
    model_path: maggie/models/stt/whisper-base.en
    model_size: base
    parallel_processing: true
    sample_rate: 16000
    simd_optimization: true
    tensor_cores_enabled: true
  whisper_streaming:
    auto_submit: false
    batch_processing: true
    buffer_size_seconds: 30.0
    compute_type: float16
    cuda_streams: 2
    dedicated_threads: 2
    enabled: true
    language: en
    low_latency_mode: true
    model_name: base
    result_timeout: 0.5
    silence_threshold: 2.0
    tensor_cores_enabled: true
    thread_affinity_enabled: true
tts:
  amp_optimization_level: O2
  buffer_size: 4096
  cache_dir: \maggie\cache\tts
  cache_size: 200
  cuda_graphs_enabled: true
  dedicated_threads: 2
  dynamic_memory_management: true
  gpu_acceleration: true
  gpu_device: 0
  gpu_precision: mixed_float16
  max_batch_size: 64
  max_workers: 4
  model_path: maggie/models/tts
  realtime_priority: true
  sample_rate: 22050
  simd_optimization: true
  spectral_processing_on_gpu: true
  tensor_cores_enabled: true
  thread_affinity_cores:
  - 8
  - 9
  thread_affinity_enabled: true
  use_cache: true
  voice_model: af_heart
  voice_preprocessing: true
