[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maggie"
version = "0.1.0"
description = "Maggie AI Assistant - Finite State Machine AI Assistant with modular utilities"
readme = "README.md"
requires-python = ">=3.10, <3.11"  # Changed from ">=3.10" to explicitly require Python 3.10.x
license = {text = "MIT"}
authors = [
    {name = "Anthony Formosa", email = "emailformosa@gmail.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "pvporcupine == 2.2.0",
    "SpeechRecognition == 3.10.0",
    "PyAudio == 0.2.13",
    "whisper_streaming == 0.2.1",
    "faster-whisper == 0.9.0",
    "kokoro == 0.8.4",
    "ctransformers == 0.2.27",
    "llama-cpp-python == 0.2.11",
    "PyQt6 == 6.5.0",
    "python-docx == 0.8.11",
    "transitions == 0.9.0",
    "numpy == 1.26.4",
    "PyYAML == 6.0",
    "loguru == 0.7.0",
    "soundfile == 0.12.1",
    "requests == 2.31.0",
    "tqdm == 4.66.1",
    "psutil == 5.9.5",
    "mammoth == 1.7.0",
]

[project.optional-dependencies]
gpu = [
    "torch >= 2.0.1",  # Base requirement without CUDA specificity
    "onnxruntime-gpu == 1.15.1",
    "kokoro @ git+https://github.com/hexgrad/kokoro",
]
cuda118 = [
    "torch == 2.0.1+cu118",  # Specific CUDA 11.8 build
]
dev = [
    "pytest >= 7.0.0",
    "black >= 23.0.0",
    "isort >= 5.0.0",
    "flake8 >= 6.0.0",
]

[project.urls]
"Homepage" = "https://github.com/formosa/maggie"
"Bug Tracker" = "https://github.com/formosa/maggie/issues"

[tool.setuptools]
packages = ["maggie", "maggie.utils"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100

[tool.flake8]
max-line-length = 100
exclude = [".git", "__pycache__", "build", "dist"]