# -*- coding: utf-8 -*-
"""
Test script for kokoro_onnx TTS functionality.

If you encounter UnicodeDecodeError, try one of these solutions:
1. Set the PYTHONIOENCODING environment variable to utf-8:
   - On Windows: set PYTHONIOENCODING=utf-8
   - On Linux/Mac: export PYTHONIOENCODING=utf-8
2. Reinstall the kokoro-onnx package:
   - pip uninstall kokoro-onnx
   - pip install kokoro-onnx --no-cache-dir
"""
import soundfile as sf
import os
import sys

import sounddevice as sd
from kokoro_onnx import Kokoro
from misaki import en, espeak

# Misaki G2P with espeak-ng fallback
fallback = espeak.EspeakFallback(british=False)
g2p = en.G2P(trf=False, british=False, fallback=fallback)

# Kokoro - fixed path handling using os.path.join and raw strings
model_dir = r"C:\\AI\\claude\\service\\maggie\\maggie\\models\\tts"
kokoro_model = os.path.join(model_dir, "kokoro-v1.0.onnx")
kokoro_weights = os.path.join(model_dir, "voices-v1.0.bin")
kokoro = Kokoro(kokoro_model, kokoro_weights)

samples, sample_rate = kokoro.create(
    "Hello. This audio generated by kokoro!", voice="af_sarah", speed=1.0, lang="en-us"
)
print("Playing audio...")
sd.play(samples, sample_rate)
sd.wait()